services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - IN_DOCKER=true
      - SECRET_KEY=kobby-dan-014
      - ALGORITHM=HS256
      - DB_USER=postgres
      - DB_PASSWORD=kobby-dan-014
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=titanic_db
    volumes:
      - ./backend:/backend
      - ./backend/data:/backend/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kobby-dan-014
      - POSTGRES_DB=titanic_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge